### PR TITLE
Allow using BGP Control Plane

### PR DESCRIPTION
**Pull request by robertvolkmann**
**How to categorize this PR?**
/area networking
/kind api-change

**What this PR does / why we need it**:
The BGP Control Plane allows us to announce the PodCIDR and the LoadBalancer IPs over BGP in a bare-metal environment.

**Special notes for your reviewer**:
https://docs.cilium.io/en/stable/network/bgp-control-plane/

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @robertvolkmann for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by axel7born — APPROVED** [review]

**Pull request merged**
