### PR TITLE
Adapt the deployment priorityClassName according to the gardener documentation

### PR DESCRIPTION
**Pull request by kris94**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
This PR removes the old PriorityClass from the charts and adapt the deployment priorityClassName according to the gardener documentation. Part of [#5634](https://github.com/gardener/gardener/issues/5634)
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```breaking operator
This version of gardener-extension-networking-cilium requires Gardener v1.50+. 
```

### CODE REVIEW

**Review by DockToFuture — COMMENTED** [review]
`scheduling.k8s.io/v1` is also used under:
- charts/internal/cilium/charts/utils-templates/templates/_versions.tpl
- charts/internal/cilium-monitoring/charts/util-templates/templates/_versions.tpl

Shouldn't this be removed as well?

**Comment by kris94** [comment]
I don't see `scheduling.k8s.io/v1` to be used anywhere else in the project.

**Review by ScheererJ — COMMENTED** [review]
Looks good, but needs a rebase.

**Comment by DockToFuture** [comment]
> I don't see `scheduling.k8s.io/v1` to be used anywhere else in the project.

You are right it was a symlink. 👍

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
