### PR TITLE
Extend configuration to support metal-stack cloud provider.

### PR DESCRIPTION
**Pull request by Gerrit91**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:

This PR adds few more fields required for the cilium extension to integrate well with metal-stack. These are:

- IPv4NativeRoutingCIDR: Enables native routing mode in order to leverage routing capabilities of our network setup without the need of tunneling
- BPFLoadBalancingMode: Allows configuring DSR mode, which has some attractive traits like preserving original source IPs from external traffic and avoiding an extra hop for the reply to external requests
- Devices: Necessary due to our BGP unnumbered approach where the node IP is sitting on the lo device for peering with leaf switches
- MTU: Falsely determined when it cannot be specified explicitly for the setup as described for field "Devices"

The PR also adds PSPs for Hubble because these are missing for some reason.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @Gerrit91 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by Gerrit91** [comment]
I have now run this version of the extension in the provider-local setup. It's working without any hacks! To test the changes further, I also modified the MTU, which was working too.

It not possible for me to test this build on our real Gardener landscape, which is still on g/g v1.42 and therefore incompatible with the current head of this extension. However, the PR is based on a branch that we made on an earlier version of this extension, which I verified is working: https://github.com/metal-stack/gardener-extension-networking-cilium/pull/1

**Review by DockToFuture — DISMISSED** [review]
/lgtm

**Comment by DockToFuture** [comment]
Thank you for the PR, I tested it on a gardener cluster and it worked well! Can you please also run `make generate` and add the generated files.

**Comment by Gerrit91** [comment]
Hey @DockToFuture, thanks for taking a look. Sorry for the delay, I am now back from vacation so I can react faster now to comments. I rebased this pull request to latest master, the generated files did not really differ from what was there before though.

**Comment by DockToFuture** [comment]
When I run `make generate` I get another chart value for example/controller-registration.yaml. The rest is the same.

**Comment by DockToFuture** [comment]
Can you update the `example/controller-registration.yaml` @Gerrit91 so that we get the PR merged?

**Comment by Gerrit91** [comment]
Hey. 

I am a bit puzzled because my `make generate` creates a different controller registration and claims this one to be correct even when running `make verify-extended`. I even unpacked the helm chart (`$chart | base64 -d | gzip -d | tar xf -`) and did a recursive directory diff. There was no difference in the chart files. 

Rebased the PR now and just removed the changed controller-registration.yaml. 

Do you have any idea what could cause this behavior? I am running on Ubuntu 22.04, go 1.19, removed the `hack/tools/bin` folder to ensure dependencies are correct... :(

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
