### PR TITLE
update cilium to v1.14.5

### PR DESCRIPTION
**Pull request by DockToFuture**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Update cilium to `v1.14.5`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Update cilium to `v1.14.5`.
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
Looking at changes in `install/kubernetes/cilium` in https://github.com/cilium/cilium/compare/v1.14.4...v1.14.5/install/kubernetes/cilium, there are a few changes in the manifests that allow changing some configuration paramters via values.yaml, e.g. resource requests or volume mounts. Do we want to take that over as well to be closer to the source?

**Comment by DockToFuture** [comment]
> Looking at changes in `install/kubernetes/cilium` in [cilium/cilium@v1.14.4...v1.14.5/install/kubernetes/cilium](https://github.com/cilium/cilium/compare/v1.14.4...v1.14.5/install/kubernetes/cilium), there are a few changes in the manifests that allow changing some configuration paramters via values.yaml, e.g. resource requests or volume mounts. Do we want to take that over as well to be closer to the source?

I would leave the PR as it is as the fields are not used right now and plead to adapt the cilium charts at a later point in time in a separate PR.

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
